version: 2.7.0-release-{build}
image: Visual Studio 2017
configuration: Release
before_build:
- ps: '& .\appveyor-prebuild.ps1'
build:
  project: SafeguardDotNet.sln
  publish_nuget: true
  parallel: true
  verbosity: normal
deploy:
- provider: NuGet
  api_key:
    secure: weO0O7MnQecxmMNErE6FEp+ZOeIAsMY1bWM017ZPX9Q5UTdXRSYtPHHoLMKDOfOW
notifications:
- provider: Email
  to:
  - petrsnd@gmail.com
  subject: SafeguardDotNet build is failing
  on_build_success: false
  on_build_failure: true
  on_build_status_changed: false
